name: CD / Deploy

on:
  # Only trigger, when the build workflow succeeded
  workflow_run:
    workflows: [CI frontend, CI backend]
    types: [completed]

jobs:
  # Deploy on VM
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: run compose up
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: net-nurture.com
          username: nuhgooyin
          key: ${{ secrets.P_KEY }}
          port: 22
          script: |
            echo "${{ secrets.CR_PAT }}" | sudo docker login https://ghcr.io -u ${{ github.actor }} --password-stdin
            sudo docker compose down
            sudo docker compose pull && sudo docker compose up -d
